.TH "driver_ff.DriverFirefox" 3 "Tue Jun 2 2020" "Version 1.0" "BigBlueButton-Attendance" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver_ff.DriverFirefox
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, headless=False)"
.br
.ti -1c
.RI "def \fBgoto\fP (self, site)"
.br
.ti -1c
.RI "def \fBclick\fP (self, xpath)"
.br
.ti -1c
.RI "def \fBsend_keys\fP (self, xpath, keys)"
.br
.ti -1c
.RI "def \fBget_value\fP (self, xpath, attribute)"
.br
.ti -1c
.RI "def \fBis_selected\fP (self, xpath)"
.br
.ti -1c
.RI "def \fBrefresh\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBheadless\fP"
.br
.ti -1c
.RI "\fBdriver\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BigBlueButton-Attendance from the source code\&.
