.TH "main" 3 "Tue Jun 2 2020" "Version 1.0" "BigBlueButton-Attendance" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEngine\fP"
.br
.RI "\fBEngine\fP behind the program\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBe\fP = \fBEngine\fP('config')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main file 
.SH "Author"
.PP 
Generated automatically by Doxygen for BigBlueButton-Attendance from the source code\&.
