.TH "main.Engine" 3 "Tue Jun 2 2020" "Version 1.0" "BigBlueButton-Attendance" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.Engine \- \fBEngine\fP behind the program\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, file_name)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "def \fBjoin_sesssion\fP (self)"
.br
.RI "Joins a session\&. "
.ti -1c
.RI "def \fBget_current_users\fP (self)"
.br
.RI "Gets the list of current users\&. "
.ti -1c
.RI "def \fBput_attendance\fP (self)"
.br
.RI "Puts attendancein a spreadsheet\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdriver\fP"
.br
.RI "Firefox driver\&. "
.ti -1c
.RI "\fBsettings\fP"
.br
.RI "Dictionary used to store settings\&. "
.ti -1c
.RI "\fBusers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBEngine\fP behind the program\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BigBlueButton-Attendance from the source code\&.
