.TH "spreadsheets_driver.SpreadSheetDriver" 3 "Tue Jun 2 2020" "Version 1.0" "BigBlueButton-Attendance" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spreadsheets_driver.SpreadSheetDriver
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, spread_sheet_type, file_name, sheet_name)"
.br
.ti -1c
.RI "def \fBsave\fP (self)"
.br
.ti -1c
.RI "def \fBread\fP (self, row, col)"
.br
.ti -1c
.RI "def \fBwrite\fP (self, row, col, value)"
.br
.ti -1c
.RI "def \fBget_row\fP (self, value, col)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfile_name\fP"
.br
.ti -1c
.RI "\fBwb\fP"
.br
.ti -1c
.RI "\fBws\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BigBlueButton-Attendance from the source code\&.
